version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest-browsers
    environment:
      GIT_COMMIT_DESC: git log --format=oneline -n 1 $CIRCLE_SHA1

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      
      - run:
          name: configure_git
          command: ci/scripts/git_config.sh

      - run:
          name: build
          command: ci/scripts/build.sh
